/** Standardised error codes used across all server → client ROOM_ERROR emissions */
export const ERROR_CODE = {
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_DATA: 'INVALID_DATA',
  INTERNAL: 'INTERNAL',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  JOIN_FAILED: 'JOIN_FAILED',
  NOT_IN_ROOM: 'NOT_IN_ROOM',
  NOT_OWNER: 'NOT_OWNER',
  NO_PERMISSION: 'NO_PERMISSION',
  SET_ROLE_FAILED: 'SET_ROLE_FAILED',
  QUEUE_FULL: 'QUEUE_FULL',
  STREAM_FAILED: 'STREAM_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  NO_VOTE_NEEDED: 'NO_VOTE_NEEDED',
  VOTE_IN_PROGRESS: 'VOTE_IN_PROGRESS',
  ALREADY_VOTED: 'ALREADY_VOTED',
  LOCAL_AUDIO_NOT_FOUND: 'LOCAL_AUDIO_NOT_FOUND',
  LOCAL_AUDIO_INVALID: 'LOCAL_AUDIO_INVALID',
  LOCAL_AUDIO_QUOTA_EXCEEDED: 'LOCAL_AUDIO_QUOTA_EXCEEDED',
  LOCAL_AUDIO_PROCESSING_FAILED: 'LOCAL_AUDIO_PROCESSING_FAILED',
  LOCAL_AUDIO_NOT_READY: 'LOCAL_AUDIO_NOT_READY',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]

export type MusicSource = 'netease' | 'tencent' | 'kugou' | 'bilibili'

/** Track origin. MusicSource intentionally remains limited to online platforms. */
export type TrackSource = MusicSource | 'local'

export type AutoFallbackStatus = 'trying' | 'success' | 'failed'

export type AutoFallbackReasonType = 'VIP_REQUIRED' | 'COPYRIGHT_RESTRICTED' | 'NO_RESOURCE' | 'TIMEOUT' | 'UNKNOWN'

export interface RoomAutoFallbackEvent {
  /** Correlates trying/success/failed toasts */
  attemptId: string
  status: AutoFallbackStatus
  fromSource: Exclude<MusicSource, 'kugou' | 'bilibili'>
  toSource: Exclude<MusicSource, 'kugou' | 'bilibili'>
  trackTitle: string
  reasonType?: AutoFallbackReasonType
  /** Safe, short detail suitable for UI (no URLs/cookies/stack traces). */
  reasonDetail?: string
}

export type UserRole = 'owner' | 'admin' | 'member'

export type PlayMode = 'sequential' | 'loop-all' | 'loop-one' | 'shuffle'

/** 音频质量档位 (kbps)：标准 / 较高 / HQ / 无损 */
export type AudioQuality = 128 | 192 | 320 | 999

export interface Track {
  id: string
  title: string
  artist: string[]
  album: string
  duration: number
  cover: string
  source: TrackSource
  sourceId: string
  urlId: string
  /** QQ 音乐媒体文件 ID（用于拼接播放链接文件名，与 urlId 的歌曲 mid 不一定相同） */
  mediaMid?: string
  /** bilibili 视频分 P 的 cid（服务端解析播放链接时需要） */
  bilibiliCid?: number
  /** Room-local asset identifier; present only for local tracks. */
  assetId?: string
  lyricId?: string
  picId?: string
  streamUrl?: string
  /** Optional server-generated fallback URL (for example, MP3 for lossless output). */
  fallbackStreamUrl?: string
  /** Expiry shared by server-generated local-audio media URLs. */
  localAudioAccessExpiresAt?: number
  /** 是否为 VIP / 付费歌曲（可能无法播放或仅试听） */
  vip?: boolean
  /** 点歌人昵称（服务端在加入队列时注入） */
  requestedBy?: string
}

/**
 * 默认播放列表的轻量引用。完整元数据（封面/时长/专辑等）通过服务端补全接口按需获取；
 * 标题与歌手保留在引用中，供列表展示和本地搜索使用。
 */
export interface DefaultQueueTrackRef {
  /** 稳定 ID（删除/去重/排序依赖） */
  id: string
  source: TrackSource
  sourceId: string
  title: string
  artist: string[]
  /** Room-local asset identifier; present only for local tracks. */
  assetId?: string
}

/** 默认播放列表增量变更（存活期间使用；进房/晋升走全量快照 DEFAULT_QUEUE_UPDATED） */
export type DefaultQueueDelta =
  | { type: 'add'; tracks: DefaultQueueTrackRef[] }
  | { type: 'remove'; trackIds: string[] }
  | { type: 'replace'; track: DefaultQueueTrackRef }
  | { type: 'clear' }

/** Public metadata for a room-local audio asset. Filesystem paths are never exposed. */
export interface LocalAudioAsset {
  assetId: string
  title: string
  artist: string[]
  album: string
  duration: number
  /** Authenticated same-origin (or signed) cover endpoint, or an empty string. */
  cover: string
  uploadedByUserId: string
  uploadedByNickname: string
  createdAt: number
  sizeBytes: number
  /** Quality snapshot used when this asset was processed. */
  audioQuality: AudioQuality
  /** Primary playable output generated by the server. */
  primaryFormat: 'mp3' | 'flac'
  /** Whether a second MP3 output is available for compatibility fallback. */
  hasFallback: boolean
  /** Codec reported by the server-side probe/transcoder. */
  codec: string
  /** Encoded bitrate in kbps when meaningful (lossless may be omitted). */
  bitrate?: number
  /** Public lifecycle state. Processing work is represented by LocalAudioTask. */
  status: 'ready' | 'pending-delete'
}

export type LocalAudioTaskStage =
  | 'waiting-upload'
  | 'receiving'
  | 'queued'
  | 'probing'
  | 'transcoding'
  | 'ready'
  | 'failed'
  | 'cancelled'

/** Public snapshot of an upload/validation/transcoding task. */
export interface LocalAudioTask {
  taskId: string
  originalFileName: string
  uploadedByUserId: string
  uploadedByNickname: string
  /** Whether the completed asset should be inserted into the main queue. */
  addToQueue: boolean
  stage: LocalAudioTaskStage
  /** Progress in the inclusive [0, 1] range when measurable. */
  progress?: number
  receivedBytes?: number
  totalBytes?: number
  assetId?: string
  errorCode?: string
  errorMessage?: string
  createdAt: number
  updatedAt: number
}

/**
 * Storage accounting exposed to members of a room-local audio session.
 *
 * `roomBytes` and `serverBytes` count completed assets. `tempBytes` is the
 * reservation for uploads that have not finished processing yet. Keeping the
 * limits in the same DTO lets the client render quota indicators without
 * duplicating deployment configuration.
 */
export interface LocalAudioUsage {
  /** Server-authoritative per-file upload limit for this deployment. */
  maxUploadBytes: number
  roomBytes: number
  roomLimitBytes: number
  serverBytes: number
  serverLimitBytes: number
  tempBytes: number
  tempLimitBytes: number
}

/** Complete room-local audio snapshot sent over REST and Socket.IO. */
export interface LocalAudioState {
  assets: LocalAudioAsset[]
  tasks: LocalAudioTask[]
  usage: LocalAudioUsage
}

/** Backward-compatible name used by the first client adapter. */
export type LocalAudioSnapshot = LocalAudioState

/** 已播放的歌曲记录 */
export interface PlayedTrack {
  /** 歌曲完整信息 */
  track: Track
  /** 播放时间戳（ms） */
  playedAt: number
  /** 点歌人昵称 */
  requestedBy?: string
}

/** 客户端可见的房间状态 */
export interface RoomState {
  id: string
  name: string
  creatorId: string
  hostId: string
  hasPassword: boolean
  /** 密码明文（仅房间内成员可见） */
  password?: string | null
  audioQuality: AudioQuality
  users: User[]
  queue: Track[]
  currentTrack: Track | null
  playState: PlayState
  playMode: PlayMode
  /** 默认播放列表池，主队列为空时从中随机抽取（房主手动维护，不被消费） */
  defaultQueue: DefaultQueueTrackRef[]
  /** 播完自动移出队列（房主开关，默认开启） */
  autoRemovePlayed: boolean
  /** 点赞模式（房主开关，需 autoRemovePlayed 开启，默认开启） */
  songLikes: boolean
  /** 房间持久化：开启后即使无人也不会被自动删除 */
  persistent: boolean
  /** 持久化房间的 TTL（小时），0 = 永不清除，上限 168 小时 */
  persistentTtlHours: number
  /** 点赞数据：trackId → 点赞用户ID列表 */
  trackLikes: Record<string, string[]>
  /** 投票通过率 (0.01–1.0)，默认 0.67 */
  voteThreshold: number
  /** 主队列最大歌曲数（房主可调，默认 200） */
  maxQueueSize: number
  /** 已播放歌曲历史记录 */
  playedHistory: PlayedTrack[]
}

export interface PlayState {
  isPlaying: boolean
  currentTime: number
  serverTimestamp: number
}

/**
 * Scheduled action payload — server tells clients to execute an action
 * at a specific future server-time, so all clients act in unison.
 */
export interface ScheduledPlayState extends PlayState {
  /** Server-clock timestamp at which clients should execute this action */
  serverTimeToExecute: number
}

export interface User {
  id: string
  nickname: string
  role: UserRole
}

export interface ChatMessage {
  id: string
  userId: string
  nickname: string
  content: string
  timestamp: number
  type: 'user' | 'system'
}

export type VoteAction = 'pause' | 'resume' | 'next' | 'prev' | 'set-mode' | 'play-track' | 'remove-track'

export interface VoteState {
  id: string
  action: VoteAction
  initiatorId: string
  initiatorNickname: string
  votes: Record<string, boolean>
  requiredVotes: number
  totalUsers: number
  expiresAt: number
  /** Optional payload for parameterized actions (e.g. target play mode) */
  payload?: Record<string, unknown>
}

/** 房间列表项 -- 用于首页房间大厅展示（轻量，不含完整 queue/users） */
export interface RoomListItem {
  id: string
  name: string
  hasPassword: boolean
  userCount: number
  currentTrackTitle: string | null
  currentTrackArtist: string | null
}

/** 平台认证状态（前端展示用，不含 cookie 明文） */
export interface PlatformAuthStatus {
  platform: MusicSource
  /** 该平台已登录的用户数 */
  loggedInCount: number
  /** 是否有 VIP 用户 */
  hasVip: boolean
  /** 最高 VIP 等级 (0=无, 1=VIP, 11=黑胶) */
  maxVipType: number
  /** 最早的 VIP 用户登录时间戳 (ms) */
  earliestVipTimestamp?: number
}

/** 当前用户自己在某平台的认证信息 */
export interface MyPlatformAuth {
  platform: MusicSource
  loggedIn: boolean
  nickname?: string
  vipType?: number
}

/** 歌单元数据（用于歌单列表展示） */
export interface Playlist {
  id: string
  name: string
  cover: string
  trackCount: number
  source: MusicSource
  creator?: string
  description?: string
}

/**
 * Queue delta sent via QUEUE_UPDATED — the client applies this incrementally
 * instead of replacing the entire queue array, saving bandwidth on large queues.
 */
export type QueueDelta =
  | { type: 'clear' }
  | { type: 'insert'; tracks: Track[]; atIndex: number }
  | { type: 'remove'; trackIds: string[] }
  | { type: 'replace'; track: Track; atIndex: number }
  | { type: 'reorder'; trackIds: string[] }
